{% set name = "candlewick" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Simple-Robotics/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec43aa84ce98ef94c5d51753689c5a666722906f010892f06d09694ea204ef2b

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - pkg-config
    - make   # [not win]
    - clang  # [win]
    - ninja  # [win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - coal
    - eigen
    - eigenpy
    - entt
    - ffmpeg
    - fmt
    - magic_enum
    - nlohmann_json
    - pinocchio
    - python
    - sdl3
  run:
    - python

test:
  imports:
    - candlewick
    - candlewick.multibody

about:
  home: https://github.com/Simple-Robotics/candlewick
  summary: 'Candlewick: a WIP renderer based on SDL_gpu'
  description: |
    Candlewick comes with a set of graphical, interaction, and utility features such as
    Shadow mapping using directional shadow maps, Screen-space ambient occlusion (SSAO)
    , Screen-space shadows (SSS), Integration with ImGui
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/Simple-Robotics/candlewick
  dev_url: https://github.com/Simple-Robotics/candlewick

extra:
  recipe-maintainers:
    - ManifoldFR
    - ymontmarin
